"""New field cep

Revision ID: 1ac1b8699d98
Revises: f1e20c8acefe
Create Date: 2024-12-18 15:50:31.280580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ac1b8699d98'
down_revision: Union[str, None] = 'f1e20c8acefe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orphanages', sa.Column('cep', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orphanages', 'cep')
    # ### end Alembic commands ###
