"""Add new tables

Revision ID: 4be7e89699cd
Revises: 
Create Date: 2024-12-17 19:37:34.970947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4be7e89699cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_associates_email'), 'associates', ['email'], unique=True)
    op.create_index(op.f('ix_associates_id'), 'associates', ['id'], unique=False)
    op.create_index(op.f('ix_associates_name'), 'associates', ['name'], unique=False)
    op.create_table('orphanages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orphanages_id'), 'orphanages', ['id'], unique=False)
    op.create_index(op.f('ix_orphanages_name'), 'orphanages', ['name'], unique=True)
    op.create_table('dependents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('orphanage_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['orphanage_id'], ['orphanages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependents_id'), 'dependents', ['id'], unique=False)
    op.create_index(op.f('ix_dependents_name'), 'dependents', ['name'], unique=False)
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('associate_id', sa.Integer(), nullable=True),
    sa.Column('orphanage_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['associate_id'], ['associates.id'], ),
    sa.ForeignKeyConstraint(['orphanage_id'], ['orphanages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_id'), 'donations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donations_id'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_dependents_name'), table_name='dependents')
    op.drop_index(op.f('ix_dependents_id'), table_name='dependents')
    op.drop_table('dependents')
    op.drop_index(op.f('ix_orphanages_name'), table_name='orphanages')
    op.drop_index(op.f('ix_orphanages_id'), table_name='orphanages')
    op.drop_table('orphanages')
    op.drop_index(op.f('ix_associates_name'), table_name='associates')
    op.drop_index(op.f('ix_associates_id'), table_name='associates')
    op.drop_index(op.f('ix_associates_email'), table_name='associates')
    op.drop_table('associates')
    # ### end Alembic commands ###
