"""Add fields

Revision ID: 925254e8968e
Revises: 4be7e89699cd
Create Date: 2024-12-18 10:43:16.105620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '925254e8968e'
down_revision: Union[str, None] = '4be7e89699cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('associates', sa.Column('document', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'associates', ['document'])
    op.add_column('dependents', sa.Column('document', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'dependents', ['document'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dependents', type_='unique')
    op.drop_column('dependents', 'document')
    op.drop_constraint(None, 'associates', type_='unique')
    op.drop_column('associates', 'document')
    # ### end Alembic commands ###
