"""New fieds orphanages

Revision ID: f5aa74eae413
Revises: 1ac1b8699d98
Create Date: 2024-12-18 16:09:11.187554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5aa74eae413'
down_revision: Union[str, None] = '1ac1b8699d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orphanages', sa.Column('state', sa.String(), nullable=False))
    op.add_column('orphanages', sa.Column('city', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orphanages', 'city')
    op.drop_column('orphanages', 'state')
    # ### end Alembic commands ###
